services:
  # Backend Java-Spring
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fomalhaut-backend
    ports:
      - "20001:20001"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_PORT=20001
    networks:
      - fomalhaut-network
    restart: unless-stopped

  # Frontend React
  frontend:
    build:
      context: ./Fomalhaut
      dockerfile: Dockerfile
    container_name: fomalhaut-frontend
    ports:
      - "20002:20001"
    environment:
      - VITE_API_URL=http://localhost:20001/api
    networks:
      - fomalhaut-network
    restart: unless-stopped

  # Grafana
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=teidesat
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_NAME=Main Org.
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      - GF_INSTALL_PLUGINS=yesoreyeram-infinity-datasource,operato-windrose-panel
    networks:
      - fomalhaut-network
    ports:
      - "3000:3000"
    volumes:
      - ./Fomalhaut/provisioning:/etc/grafana/provisioning
      - ./Fomalhaut/dashboards-grafana:/var/lib/grafana/dashboards
    user: "${HOST_UID}:${HOST_GID}"

networks:
  fomalhaut-network:
    driver: bridge
